W5D1/music_app_test/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[create new show]

  resource :session, only: %i[create new destroy]

  resources :bands
end

W5D1/music_app_test/app/models/album.rb
class Album < ApplicationRecord

  validates :title, :year, :band_id, presence: update_attributes
  validates :recording_type, presence: true, inclusion: { in: %w(studio live),
                                                          message: 'Invalid recording type' }

  belongs_to :band,
  class_name: :Band,
  foreign_key: :band_id
end

W5D1/music_app_test/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  has_many :albums,
  class_name: :Album,
  foreign_key: :band_id
end

W5D1/music_app_test/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#
require 'bcrypt'
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates  :password_digest, presence: { message: 'Password can\'t be blank' }
  validates :password, length:  {minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && BCrypt::Password.new(user.password_digest).is_password?(password)
    nil
  end

  private
  attr_reader :password
end

W5D1/music_app_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil unless session[:session_token].present?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

W5D1/music_app_test/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["Not a valid band name"]
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W5D1/music_app_test/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    # debugger
    if user
      login_user!(user)
      flash[:success] = ["Successfully signed in!"]
      redirect_to bands_url
    else
      flash[:errors] = ['Invalid login credentials']
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    logout_user!
    flash[:success] = ["Successfully logged out!"]
    redirect_to new_session_url
  end

end

W5D1/music_app_test/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = ['Successfully created account!']
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid email or password"]
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music_app_test/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app_test/app/views/bands/edit.html.erb
<h2>Edit Band</h2>
<br>
<form class="" action="<%=band_url(@band)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <input type="hidden" name="_method" value="patch">

  <label for="band_name">Band Name</label>
  <input id="band_name" type="text" name="band[name]" value="<%=@band.name%>">
  <br>

  <input type="submit" value="Edit Band">
</form>

W5D1/music_app_test/app/views/bands/index.html.erb
<h1>All The Bands</h1>

<% @bands.each do |band| %>
  <ul>
    <li>
      <a href="<%=band_url(band)%>"><%= band.name %></a>
    </li>
  </ul>
  <br>
<% end %>
<a href="<%=new_band_url%>">Add A Band</a>

W5D1/music_app_test/app/views/bands/new.html.erb
<h1>Add A Band</h1>
<br>
<form class="" action="<%=bands_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="band_name">Band Name</label>
  <input id="band_name" type="text" name="band[name]" value="">
  <br>

  <input type="submit" value="Add Band">
</form>

W5D1/music_app_test/app/views/bands/show.html.erb
<h2><%=@band.name%> Is Here</h2>
<br>

<a href="<%=edit_band_url(@band)%>">Edit Band</a>
<br>

<form class="" action="<%=band_url(@band)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Band">
</form>

W5D1/music_app_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="main-title">
      <h1>Music App</h1>
    </header>
    <% if logged_in? %>
      <nav>
        <%= "Welcome, #{current_user.email}" %>

        <br>
        <form class="" action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Log Out">
        </form>
      <% else %>
        <a href="<%= new_user_url %>">Sign Up</a>
        <a href="<%= new_session_url %>">Sign In</a>
      <% end %>
      </nav>

    <br>

    <a href="<%=bands_url%>">See All Bands</a>
    <%= yield %>
  </body>
</html>

W5D1/music_app_test/app/views/users/new.html.erb
<h1>Music App</h1>

<br>

<h2>Sign Up</h2>

<br>
<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="">

  <br>

  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]" value="">

  <br>

  <input type="submit" value="Sign Up">
</form>

W5D1/music_app_test/app/views/users/show.html.erb
<h2><%= @user.email %>'s Page</h2>